// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_client from "./routes/api/client.ts";
import * as $api_invoice from "./routes/api/invoice.ts";
import * as $client_create_index from "./routes/client/create/index.tsx";
import * as $client_index from "./routes/client/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $invoice_create from "./routes/invoice/create.tsx";
import * as $client_list from "./islands/client-list.tsx";
import * as $form_client from "./islands/form-client.tsx";
import * as $form_invoice from "./islands/form-invoice.tsx";
import * as $invoice_list from "./islands/invoice-list.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/client.ts": $api_client,
    "./routes/api/invoice.ts": $api_invoice,
    "./routes/client/create/index.tsx": $client_create_index,
    "./routes/client/index.tsx": $client_index,
    "./routes/index.tsx": $index,
    "./routes/invoice/create.tsx": $invoice_create,
  },
  islands: {
    "./islands/client-list.tsx": $client_list,
    "./islands/form-client.tsx": $form_client,
    "./islands/form-invoice.tsx": $form_invoice,
    "./islands/invoice-list.tsx": $invoice_list,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
